export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';
export const TITLE_CHANGED = 'TITLE_CHANGED';

export const COMIC_ON_LODING = 'COMIC_ON_LODING';
export const COMIC_SUCCEDED = 'COMIC_SUCCEDED';
export const COMIC_FAILED = 'COMIC_FAILED';
