export const COMIC_ON_LODING = 'COMIC_ON_LODING';
export const COMIC_SUCCEDED = 'COMIC_SUCCEDED';
export const COMIC_FAILED = 'COMIC_FAILED';

export const STRIP_ON_LODING = 'STRIP_ON_LODING';
export const STRIP_SUCCEDED = 'STRIP_SUCCEDED';
export const STRIP_FAILED = 'STRIP_FAILED';
